[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "diff-motion"
version = "0.1.0"
description = "A real-time computer-vision application for UAVs"
readme = "README.md"
authors = [
    { name = "Michal Siniarski", email = "siniarskim@gmail.com" }
]
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
test = ["pytest"]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "diff_motion"
manifest-path = "crates/python/Cargo.toml"
