[package]
name = "diff-motion-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
authors = ["Michal Siniarski <siniarskim@gmail.com>"]

[features]
default = ["display"]
display = ["opencv/highgui"]

[dependencies]
opencv = { version = "0.101.0", default-features = false, features = [
    "clang-runtime",
    "features",
    "geometry",
    "imgproc",
    "video",
    "videoio",
] }
serde = { version = "1.0", features = ["derive"] }
